### PR TITLE
Mongodb crud (#7)

### PR DESCRIPTION
**Pull request by Youngestdev**
* Rewrite APIs to use MongoDB

### CODE REVIEW

**Comment by rberrelleza** [comment]
👏 👏 👏 

do we need to create a separate branch for this @Youngestdev ?

**Comment by Youngestdev** [comment]
>   
> 
> do we need to create a separate branch for this @Youngestdev ?

Ah yes, it didn't occur to me. I think I'll create a new branch so we can preserve the original code in the main branch for the first blog post. Do you mind creating a new branch `preview-environment`, @rberrelleza ?

**Comment by rberrelleza** [comment]
I think it's better to have one branch that reflects the code of each post, and then have main have the full code?

**Comment by rberrelleza** [comment]
@Youngestdev created the `preview-environment` branch

**Comment by Youngestdev** [comment]
> I think it's better to have one branch that reflects the code of each post, and then have main have the full code?

Okay, I think I agree with this. In that case, delete the new branch `preview-environment`, ( sorry for the stress ! ) and create a new branch `part-1` from the main branch. That way we can preserve the original code after merging.

@rberrelleza

**Comment by rberrelleza** [comment]
done @Youngestdev !

**Comment by Youngestdev** [comment]
> done @Youngestdev !

Thanks!. Sending in the draft tomorrow :)

**Pull request merged**
